### ISSUE TITLE
running no feature

### ISSUE THREAD

**Issue by davendw49** [JudyYe/zero-shot-gcn#7]
It's a fantastic work for zero-shot learning.
But I use basic method to run your code only showing no feature.
Would you please explain that?
![screen shot 2018-08-03 at 11 09 45 am](https://user-images.githubusercontent.com/32675226/43622251-c20c5d4a-970d-11e8-98df-4d7402fb856b.png)

**Comment by felixgwu** [comment]
Hi @davendw49,

I faced the same problem as you before. 
The reason is that if you follow the instruction, the features are put in `../feats` directly instead of `../feats/res50`. You can just create this folder and move the features into it.

`python tools/extract_pool5.py --gpu $GPU_ID &`should be `python tools/extract_pool5.py --gpu $GPU_ID --feat_dir ../feats/res50  &` instead in the instruction.
