### ISSUE TITLE
How to generate the lists using my custom dataset?

### ISSUE THREAD

**Issue by TomHeaven** [JudyYe/zero-shot-gcn#8]
Hi, I'm trying to train a model on my own data. Different from your dataset, every class  in my dataset corresponds to a `single word`. 

I try to generate files in the lists folder, about a little confused about their meanings.

I guess `all.txt`, `2-hops.txt` contain labels selected using certain criterion from words. If my guess is right, it will be easily generated.

However, the training file `train_gcn.py` still requires a file named `corresp-all.json`. So what does the jason file do?

Thanks!

**Comment by shenyingying** [comment]
excuse me,how can i get the dataset, I signup imageNet in .edu email,but i didn't have permission to the original images,i didn't know how to do next,can you share me dataset !

**Comment by xixiU** [comment]
Same problem.Haved you solved this problem?

**Comment by shenyingying** [comment]
what's problem发自我的华为手机-------- 原始邮件 --------主题：Re: [JudyYe/zero-shot-gcn] How to generate the lists using my custom dataset? (#8)发件人：xixiU 收件人：JudyYe/zero-shot-gcn 抄送：BlueSandals ,Comment Same problem.Haved you solved this problem?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/JudyYe/zero-shot-gcn","title":"JudyYe/zero-shot-gcn","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/JudyYe/zero-shot-gcn"}},"updates":{"snippets":[{"icon":"PERSON","message":"@xixiU in #8: Same problem.Haved you solved this problem?"}],"action":{"name":"View Issue","url":"https://github.com/JudyYe/zero-shot-gcn/issues/8#issuecomment-420849167"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/JudyYe/zero-shot-gcn/issues/8#issuecomment-420849167",
"url": "https://github.com/JudyYe/zero-shot-gcn/issues/8#issuecomment-420849167",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [JudyYe/zero-shot-gcn] How to generate the lists using my custom dataset? (#8)",
"sections": [
{
"text": "",
"activityTitle": "**xixiU**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@xixiU",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"JudyYe/zero-shot-gcn\",\n\"issueId\": 8,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"JudyYe/zero-shot-gcn\",\n\"issueId\": 8\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/JudyYe/zero-shot-gcn/issues/8#issuecomment-420849167"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 371693426\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by JudyYe** [comment]
#14
